export enum GoogleLabel {
  Inbox = 'INBOX',
  Sent = 'SENT',
  Spam = 'SPAM',
  Trash = 'TRASH',
  Important = 'IMPORTANT',
  Draft = 'DRAFT',
  Starred = 'STARRED',
  Unread = 'UNREAD',
  Chat = 'CHAT',
  CategoryPersonal = 'CATEGORY_PERSONAL',
  CategoryPromotions = 'CATEGORY_PROMOTIONS',
  CategorySocial = 'CATEGORY_SOCIAL',
  CategoryUpdates = 'CATEGORY_UPDATES',
  CategoryForums = 'CATEGORY_FORUMS',
}
